version: "3.9"
services:
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "80:3000"
  backend:
    build: backend
    depends_on:
      - db
      - broker
    env_file:
      - "backend/.env"
    ports:
      - "12666:12666/udp"
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - "./db/data:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./broker/password_file:/mosquitto/password_file"
      - "./broker/log:/mosquitto/log"
      - "./broker/data:/mosquitto/data"
  explorer:
    image: smeagolworms4/mqtt-explorer
    depends_on:
      - broker
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - "./broker/explorer:/mqtt-explorer/config"