version: "3.9"
services:
  frontend:
    build: frontend
    ports:
        - "8000:80"
  db:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=secret
    volumes:
        - "./db/data:/var/lib/mysql"
  broker:
    image: eclipse-mosquitto
    ports:
        - "1883:1883"
        - "9001:9001"
    volumes:
        - "./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
        - "./broker/mosquitto.log:/mosquitto/mosquitto.log"
        - "./broker/data:/mosquitto/data"
    profiles:
        - test